# Generated by Django 4.1 on 2022-10-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postcomment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isapplyforjoin',
            field=models.BooleanField(default=False),
        ),
    ]
