# Generated by Django 4.1 on 2022-10-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_followers_count_and_more'),
        ('posts', '0006_post_isapplyforjoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='participants',
            field=models.ManyToManyField(default=0, related_name='post_participant', to='users.userprofile'),
        ),
    ]
