# Generated by Django 4.1 on 2022-10-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='participants',
        ),
    ]
