# Generated by Django 4.1 on 2022-08-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
